import json
import asyncio
from turtle import title

from playwright.async_api import async_playwright


class StepExecutor:
    def __init__(self, steps, output_dir="screenshots"):
        """
        StepExecutor takes a list of LLM-generated steps and executes them
        inside a live browser using Playwright.

        Args:
            steps (list): List of step dictionaries from the LLM.
            output_dir (str): Folder where screenshots will be saved.
        """
        self.steps = steps
        self.output_dir = output_dir

    async def run(self):
        """
        Main execution function.
        Opens a browser, loops through all steps, performs actions,
        and captures screenshots.
        """

        # Start Playwright engine (browser automation)
        async with async_playwright() as p:

            # Launch Chromium browser (headless=False = show UI)
            browser = await p.chromium.launch(headless=False)

            # Create an isolated browser context (like a fresh profile)
            context = await browser.new_context(storage_state="notion_state.json")

            # Open a new blank tab
            page = await context.new_page()

            # Loop through each step generated by your LLM
            for idx, step in enumerate(self.steps):

                # Extract fields from the step
                action = step.get("action")
                selector = step.get("selector")
                value = step.get("value")
                description = step.get("description", f"step_{idx+1}")

                print(f"\n▶ Executing step {idx+1}: {step}")

                try:
                    # -------------------------
                    # ACTION: Go to a webpage
                    # -------------------------
                    if action == "goto":
                        # Navigate to URL and wait for basic DOM load
                        await page.goto(value, wait_until="domcontentloaded")

                    # -------------------------
                    # ACTION: Click an element
                    # -------------------------
                    elif action == "click":
                        # Click on a CSS selector
                        await page.click(selector)

                    # -------------------------
                    # ACTION: Type into a field
                    # -------------------------
                    elif action == "type":
                        # Fill the input with a value (erases existing text)
                        await page.fill(selector, value)

                    # -------------------------
                    # ACTION: Wait for an element
                    # Useful for modals, menus, loading
                    # -------------------------
                    elif action == "wait_for":
                        # Wait until element appears in DOM
                        await page.wait_for_selector(selector)

                    # -------------------------
                    # ACTION: Just take a screenshot
                    # -------------------------
                    elif action == "screenshot":
                        # Manual screenshot by user instruction
                        await page.screenshot(
                            path=f"{self.output_dir}/{idx+1}_{description}.png"
                        )

                    elif action == "set_title":
                        title = page.locator('[data-testid="page-title"]').first

                        # Click the title
                        await title.click()

                        # Enter editing mode
                        await page.keyboard.press("Enter")

                        # Select all existing title text and clear it
                        await page.keyboard.press('Control+A')
                        await page.keyboard.press('Backspace')

                        # Type the new title naturally
                        await page.keyboard.type(value, delay=50)


                    # -------------------------
                    # ACTION: Hover over an element
                    # -------------------------
                    elif action == "hover":
                        await page.hover(selector)

                    # -------------------------
                    # ACTION: Press a keyboard key
                    # Example: {"action": "press", "selector": "body", "value": "Enter"}
                    # -------------------------
                    elif action == "press":
                        await page.press(selector, value)

                    # --------------------------------------------------
                    # AUTOMATIC SCREENSHOT AFTER ANY UI-CHANGING ACTION
                    # --------------------------------------------------
                    if action in ["click", "type", "goto", "hover"]:
                        await page.screenshot(
                            path=f"{self.output_dir}/{idx+1}_{description}.png"
                        )

                except Exception as e:
                    # Show error but continue running the remaining steps
                    print(f"❌ Error executing step {idx+1}: {e}")

            # After all steps, close the browser
            await browser.close()


# -------------------------
# Example run
# -------------------------

if __name__ == "__main__":

    # Example steps generated by the LLM
    # These steps can be ANYTHING depending on the incoming query
    steps = [
        {
            "action": "goto",
            "value": "https://www.notion.so",
            "description": "open_homepage"
        },
        {
            "action": "click",
            "selector": "div[aria-label='New page']",
            "description": "open_new_page"
        },
        {
            "action": "wait_for",
            "selector": "div[contenteditable='true']",
            "description": "wait_for_title_field"
        },
        {
            "action": "type_title",
            "value": "My AI Generated Page",
            "description": "enter_title"
        },
        {
            "action": "screenshot",
            "description": "screenshot_after_title"
        },
        {
            "action": "type",
            "selector": "div[contenteditable='true']",
            "value": "This is the body content.",
            "description": "enter_body_content"
        },
        {
            "action": "screenshot",
            "description": "final_state"
        }
    ]


    executor = StepExecutor(steps)
    asyncio.run(executor.run())
